export const roster:string[] = [
  "Isaiah Mucius",
  "Daivien Williamson",
  "Jake LaRavia",
  "Cameron Hildreth",
  "Dallas Walton",
  "Khadim Sy",
  "Lucas Taylor",
  "Robert McCray",
  "Alondes Williams",
  "Matthew Marsh",
  "RJ Kennah",
  "Luc Robinson",
  "Anthony Mathis",
  "Kevin Dunn",
  "Damari Monsanto",
  "Tariq Ingraham",
  "Grant van Beveren",
  "Miles Lester",
  "Carter Whitt"
];